### ISSUE TITLE
Feature Request: Add option to disable pluralization for scopes

### ISSUE THREAD

**Issue by bikramwp** [lwe/simple_enum#120]
For example in the case of a `status` field:

```
as_enum :status, {
  active: 1,
  canceled: 2,
  pending: 3
}
```

generates the scope methods `actives`, `canceleds`, `pendings`. It would be nice to be able to disable the pluralization for scopes in these cases.

If you're amenable, I'll send a pull request for this.

**Comment by lwe** [comment]
Hey, yes, if it's not adding too much complexity to the overall codebase this could be a worthy introduction. Did you consider adding custom inflections instead though?

```ruby
# config/initializers/inflections.rb
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.uncountable %w{ active canceled pending }
end
```

**Comment by mvastola** [comment]
I just ran into this issue and solved it by manually inflecting the word as uncountable, but it's not the best workaround in my use case..

Might I suggest making it possible to use a translation scoped to ActiveRecord and the model name to override the name of the scope altogether? 

In my situation, my model is `Website` and in my model I have: 
```
as_enum :type, { :standard => 0, :coming_soon => 1 }, :source => :type_cb
```
This would normally create the named scopes `Website.standards` and `Website.coming_soons`. The former is unintuitive, so it makes sense to singularize it in this case. That said, "standards" is a word and the correct (and desirable) pluralization of the word "standard", should that word ever find itself elsewhere in my app. This makes it less than ideal to define it as `uncountable`.

-----------

In general, I think adding the option to totally override the scope name via a translation adds more flexibility and clarity to some scopes.

Say, for instance, I had a model named `User` with the following code:
```
as_enum :continent, { :north_america => 0, :south_america => 1, :europe => 2, :asia => 3, :oceana => 4, :africa => 5 }
```
The ideal way to list users from a given continent wouldn't be `User.europes` or `User.europe` or even `User.continent_europe` (assuming you set `:prefix => true` *and* set `"continent_europe"` as `uncountable`). It would obviously be `User.european`. And there's no way to get Rails to arrive at that word via inflection.

**Comment by lwe** [comment]
@mvastola what is Rails doing when you have a model named Standard or Europe? Falling back to translations is rather frickle and could fail fast and in unexpected ways.

Thus I personally prefer to favor the add uncountable inflections...

**Comment by mvastola** [comment]
To be clear, I'm not suggesting that the gem "fall back" on a translation. I'm suggesting the fallback be the pluraluzed name of the enum choice if there is no translation present.

I'm not entirely clear on the technical definion of an inflection vs a translation (so apologies if I use the terms interchangibly), but they all are defined in the locale, including the methods used to pluralize words and their exceptions. 

So it's not as if we would be invoking locales whereas we weren't before. I'm also not sure exactly where your concern comes from that translations are "rather frickle and could fail fast and in unexpected ways".

---------

With the `Standard` example, let's say you had specified it as uncountable:
* The first place I imagine this would have a deleterious effect would be in the controller naming. Rails would expect the controller to be named `StandardController` instead of the intuitive/standard (no pun intended) `StandardsController`.
* The accompanying route which would normally be `resources :standards` wouldn't function. 
* Rails generators would also malfunction, naming the underlying database table `standard` instead of `standards` in generating the migration.
  * If you fixed this, you'd have to manually override the table name in the model or else `ActiveRecord` wouldn't be cognizant of the plural spelling to look for the table.
* If I wanted to use `Standard` in a `has_many` relation from another table, this wouldn't work normally either, as `has_many :standards` would be incorrect.

**Comment by lwe** [comment]
Okay, thanks for your explanation and remarks, I think I previously did not read closely enough your remark regarding standard vs standards, sorry 😄 

While I can see that `standards` might feel a bit counter-intuitive I don't think it's worth adding another / different pluralisation resource than Rails already is using. At the moment I see the following ways forward:

1. Leave as is, i.e. use inflections where appropriate (and yes it has impact on Rails too). If more control over naming is required, the scopes can be skipped and added manually by the developer - or can be aliased...
   ```ruby
   # Alias
   as_enum :continent, { north_america: 0, europe: 2 }
   self << class
      alias_method :europeans, :europes # or is the inflection #europe? 
   end

  # Skip, see with:
  as_enum :continent, { north_america: 0, europe: 2 }, with: %w{dirty attribute}
  scope :europeans, -> { where(contient_cd: self.class.continents[:europe]) }
   ```
  
   JFYI, not that I'm overly happy with this "solution" or that's it's very straight-forward readable, all I'm saying is that there is an existing solution, that might work.
2. Add the ability to better configure the scopes, i.e. having the ability to provide a map as follows:
    ```ruby
    as_enum :continent, { north_america: 0, europe: 2 }, scope_names: { europe: europeans }
    ```

   TBH - not sure if this is pretty, but this would IMO work well enough and be close to the source of definition.

The trickiest part is now that we've to figure out if it makes sense to add the complexity / additional code for solution (2) to simple_enum - or we simply say, nah - at the moment we are good enough with inflections, aliases or custom scopes... because in the end every feature added needs to be maintained, supported etc. This is why I'm usually a bit reluctant to add new features like this.

Any votes / opinions?

**Comment by mvastola** [comment]
I'm for the second option in this case. I think the use case is liable to come up often enough that it's worth adding.. 

If `prefix` is `false` (as is the default) there's the inherent assumption that a word used to describe an attribute of the model (i.e. "europe") will make sense describing the model itself (i.e. "user"). There are going to be a ton of times where this isn't the case.

Yes, you can always set `prefix` to `true`, but that's liable to generate long, unwieldy scope names (i.e. "continent_north_america"). I'm sure, if there were an option to specify your own shorter ones, it would get used.

**Comment by bikramwp** [comment]
I think the best approach would be to make the pluralization optional. The other use cases brought up in this issue are interesting, but I feel they are out of scope of this gem because there are potentially other such subtleties that can exist.

So in the interest of simplicity, since the gem adds a `pluralize` call to pluralize the accessor names )with no way to turn it off), it would be a good idea to make that optional.

**Comment by lwe** [comment]
Really dig the approach proposed by @bikramwp, good points. Now any suggestions for how we integrate this change, because at the moment we kind of have an "API contract" that looks as follows:

```
generate_enum_xxx_methods_for(enum, accessor)
```
