### ISSUE TITLE
Default value for non-ActiveRecord models

### ISSUE THREAD

**Issue by abacha** [lwe/simple_enum#88]
I'm using `as_enum` on a non-activerecord class by including it
is it possible to set a default value on an enum?

**Comment by Startouf** [comment]
The whole point of enums is to be meaningful. I'd rather be able to set default values like this

```ruby
as_enum :status, [:ok, :maintenance_needed, :broken], default: :ok
```

...rather than having to specify a default **integer** value..

**Comment by lucke84** [comment]
@Startouf +1

**Comment by lwe** [comment]
All right, it looks like a few people are interested in this feature. Following considerations:

- *A)* This only makes sense for **non** ActiveRecord models, as AR models should set the default value via Rails migration / in the DB schema and thus I do not think it makes sense to allow this for AR models
- *B)* Really like the proposal from @Startouf to allow setting it as enum value, which indeed would make sense
- *C)* This feature would then require to be implemented for MongoId and with Plain-Old-Ruby-Objects, any proposals?

**Comment by Startouf** [comment]
*  A) Yeah I guess you're right. I'm so glad I switched to Mongoid, I just can't stand migrations...
*  B) Cool
*  C) Is there going to be much difference between the Mongoid implementation and the Ruby object one ? do we want to change the `association_cd` value in the database after the field is created, or do we want the accessor to return the default value instead of nil ?

Anyway, you'll need to consider a :default key to your options hash starting from `attribute.rb`. Also, it wouldn't hurt to raise an exception of let the programmer/user know if the provided default value isn't in the enum hash.

**Comment by lwe** [comment]
To keep it simple I think both Ruby objects and Mongoid should use the same logic. For functionality like this my _accessor model_ seems to start to break, as there's a single class handling reading, writing etc., so it's hard to have different behavior. Maybe it should be refactored to a reader / writer component and then the reader can be a `DefaultValueReader` or something like that...
