### ISSUE TITLE
What is the reason for using _cd extension in fieldname?

### ISSUE THREAD

**Issue by deepakshinde** [lwe/simple_enum#94]

**Comment by lwe** [comment]
The motivation was basically the same similar to Rails' relations, with `user_id` and `user`, but basically it is to be unobtrusive, by not changing the behaviour of `xyz_cd`.

**Comment by stuarthannig** [comment]
I'd have to suggest giving a brief description in the README why this is. It's not inherently apparent.

**Comment by mattruzicka** [comment]
I would also like to know whether 'cd' is an abbreviation for something.

**Comment by lwe** [comment]
Yes, the abbreviation cd stands for _code_. We used that convention at an employer I used to work for (that was ~6 years ago).

Hope it makes a tiny little bit of sense :)

**Comment by joshuapinter** [comment]
> Yes, the abbreviation cd stands for _code_. We used that convention at an employer I used to work for (that was ~6 years ago).
> 
> Hope it makes a tiny little bit of sense :)

Okay, so basically no reason at all then. Haha. 

Just kidding. But if it were me, I would have used something like `_enum`. Hell, even if you wanted to keep it as _code_, I would have just used the full `_code` to save confusion over the cost of two extra characters.

I think the big reason people are wondering about this is, what happens if they just use the same column name as the attribute, without the `_cd`? Will it blow everything up or will it generally be okay?

Thanks!
